{% set name = "swifttools" %}
{% set version = "3.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swifttools-{{ version }}.tar.gz
  sha256: a852671be5c53d09c44fb711aeb39c5f8a08239f1acffb369b59321791290de4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - requests
    - python-jose
    - pandas
    - tabulate
    - numpy

test:
  imports:
    - swifttools

about:
  home: https://gitlab.com/DrPhilEvans/swifttools
  summary: Tools for users of the Swift satellite
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
